language: "node_js"

node_js:
  - "0.12" # Compat
  - "iojs" # Compat
  - "4.2.6" # LTS
  - "5.5.0" # Latest stable

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script: make test-coveralls